### ISSUE TITLE
Autocomplete on user reference throws 503 internal server error

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/reference#17] opened 2017-03-31 00:24 UTC
I added a user-reference field to a node. When typing in the autocomplete field, I get the following javascript error:

```
An AJAX HTTP error occurred.x
HTTP Result Code: 500
Debugging information follows.
Path: /index.php?q=reference_autocomplete/field_broadcaster-node-shows
StatusText: Internal Server Error
ResponseText: 
```

**Comment by mikemccaffrey** [comment] 2017-04-19 21:49
I'm unable to recreate this error. There are no issues when I add a reference field to a node that targets users and then use the autocomplete widget to select a user.

Is there any way that you could get the actual error from your web server logs?

**Comment by mikemccaffrey** [comment] 2017-04-20 20:14
This looks like it was probably a duplicate of #2, so closing.

**Closed by mikemccaffrey** 2017-04-20 20:14 UTC
Labels: bug
